import { getScanBySession, initDb } from '@/lib/db';
import { redirect } from 'next/navigation';
import PrintButton from './PrintButton';

export default async function SuccessPage({ searchParams }: { searchParams: { session_id?: string } }) {
  const sessionId = searchParams.session_id;
  
  if (!sessionId) redirect('/recall-report');

  await initDb();
  const scan = await getScanBySession(sessionId);

  if (!scan || scan.status !== 'paid') {
    redirect('/recall-report?error=payment_not_verified');
  }

  const reportData = JSON.parse(scan.scan_data as string);

  return (
    <main className="min-h-screen bg-slate-50 p-8 print:p-0 print:bg-white text-slate-900">
      <div className="max-w-4xl mx-auto bg-white shadow-lg rounded-lg p-8 print:shadow-none print:rounded-none">
        <header className="border-b pb-4 mb-6">
          <h1 className="text-3xl font-bold text-slate-900">RecallGuard Compliance Report</h1>
          <p className="text-slate-500">Generated for: {scan.email}</p>
          <p className="text-slate-500">Scan ID: {scan.id}</p>
        </header>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Executive Summary</h2>
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-red-50 p-4 rounded border border-red-200">
              <p className="text-sm text-red-800">High Severity</p>
              <p className="text-3xl font-bold text-red-900">{reportData.highSeverity || 0}</p>
            </div>
            <div className="bg-orange-50 p-4 rounded border border-orange-200">
              <p className="text-sm text-orange-800">Moderate Severity</p>
              <p className="text-3xl font-bold text-orange-900">{reportData.moderateSeverity || 0}</p>
            </div>
            <div className="bg-green-50 p-4 rounded border border-green-200">
              <p className="text-sm text-green-800">Cleared Items</p>
              <p className="text-3xl font-bold text-green-900">{reportData.clearedItems || 0}</p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Detailed Findings</h2>
          <pre className="bg-slate-100 p-4 rounded text-xs overflow-auto text-slate-800">
            {JSON.stringify(reportData.matches || reportData.matchedItems, null, 2)}
          </pre>
        </section>

        <footer className="mt-12 pt-6 border-t text-center text-slate-400 text-sm print:mt-24">
          <p>This is a cryptographically-styled audit report generated by RecallGuard.</p>
          <PrintButton />
        </footer>
      </div>
    </main>
  );
}
