import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 12, fontFamily: 'Helvetica' },
  header: { marginBottom: 20, borderBottom: '2 solid #000', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#666' },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 8, color: '#333' },
  row: { flexDirection: 'row', marginBottom: 5 },
  col: { flex: 1 },
  statBox: { padding: 10, borderRadius: 4, marginBottom: 10 },
  high: { backgroundColor: '#FEE2E2', border: '1 solid #EF4444' },
  moderate: { backgroundColor: '#FFEDD5', border: '1 solid #F97316' },
  cleared: { backgroundColor: '#DCFCE7', border: '1 solid #22C55E' },
  statLabel: { fontSize: 10, color: '#4B5563' },
  statValue: { fontSize: 20, fontWeight: 'bold' },
  threatBox: { padding: 10, marginBottom: 8, borderLeft: '4 solid #EF4444', backgroundColor: '#F9FAFB' },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 8, color: '#999' }
});

export const RecallReportPDF = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>RecallGuard Compliance Report</Text>
        <Text style={styles.subtitle}>Generated: {new Date().toISOString()}</Text>
        <Text style={styles.subtitle}>Scan ID: {data.scanId || 'N/A'}</Text>
        <Text style={styles.subtitle}>Crypto Verification Hash: {data.hash || 'N/A'}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <View style={{ flexDirection: 'row', gap: 10 }}>
          <View style={[styles.statBox, styles.high, { flex: 1 }]}>
            <Text style={styles.statLabel}>High Severity (FDA Class I / CPSC Critical)</Text>
            <Text style={styles.statValue}>{data.highSeverity || 0}</Text>
          </View>
          <View style={[styles.statBox, styles.moderate, { flex: 1 }]}>
            <Text style={styles.statLabel}>Moderate Severity</Text>
            <Text style={styles.statValue}>{data.moderateSeverity || 0}</Text>
          </View>
          <View style={[styles.statBox, styles.cleared, { flex: 1 }]}>
            <Text style={styles.statLabel}>Cleared Items</Text>
            <Text style={styles.statValue}>{data.clearedItems || 0}</Text>
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Detailed Findings & Required Actions</Text>
        {data.matches?.map((match: any, i: number) => (
          <View key={i} style={styles.threatBox}>
            <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>
              {match.title || match.product_name} ({match.upc || match.identifier})
            </Text>
            <Text style={{ marginBottom: 2 }}><Text style={{ fontWeight: 'bold' }}>Agency:</Text> {match.source || match.agency}</Text>
            <Text style={{ marginBottom: 2 }}><Text style={{ fontWeight: 'bold' }}>Hazard:</Text> {match.hazard}</Text>
            <Text style={{ marginBottom: 2 }}><Text style={{ fontWeight: 'bold' }}>Severity:</Text> {match.severity}</Text>
            <Text style={{ fontWeight: 'bold', color: '#B91C1C' }}>
              Action Required: Pull from shelves immediately.
            </Text>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        This document is a cryptographically verified compliance artifact generated by RecallGuard. 
        It serves as proof of due diligence for regulatory and insurance purposes.
      </Text>
    </Page>
  </Document>
);
